file_format: "1"
id: grippy_20
name: Grippy20
type: shield
url: https://github.com/calvinhenderson/grippy-20
requires:
  - xiao_d
exposes: []
features:
  - keys
siblings:
  - grippy_20_left
  - grippy_20_right
